# Dockerfile.nginx

# Usar a imagem oficial do Nginx
FROM nginx:alpine

# Remover a configuração padrão
RUN rm /etc/nginx/conf.d/default.conf

# Copiar nossa configuração personalizada
COPY nginx/default.conf /etc/nginx/conf.d/