# Generated by Django 5.2.3 on 2025-06-30 22:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "phone_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Número do Telefone"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Contato",
                "verbose_name_plural": "Contatos",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EvolutionConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "instance_name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nome da Instância"
                    ),
                ),
                (
                    "api_key",
                    models.CharField(max_length=255, verbose_name="Chave da API"),
                ),
                ("base_url", models.URLField(verbose_name="URL Base da API")),
                (
                    "webhook_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="URL do Webhook"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "is_connected",
                    models.BooleanField(default=False, verbose_name="Conectado"),
                ),
                (
                    "last_check",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Última Verificação"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Configuração Evolution",
                "verbose_name_plural": "Configurações Evolution",
                "ordering": ["instance_name"],
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nome do Grupo"),
                ),
                (
                    "group_id",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="ID do Grupo no WhatsApp",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Grupo",
                "verbose_name_plural": "Grupos",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Título")),
                ("content", models.TextField(verbose_name="Conteúdo da Mensagem")),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("text", "Texto"),
                            ("image", "Imagem"),
                            ("document", "Documento"),
                            ("audio", "Áudio"),
                        ],
                        default="text",
                        max_length=10,
                        verbose_name="Tipo de Mídia",
                    ),
                ),
                (
                    "media_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="message_media/",
                        verbose_name="Arquivo de Mídia",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Template de Mensagem",
                "verbose_name_plural": "Templates de Mensagens",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="ScheduledMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=100, verbose_name="Título do Agendamento"
                    ),
                ),
                (
                    "recipient_type",
                    models.CharField(
                        choices=[("contact", "Contato"), ("group", "Grupo")],
                        max_length=10,
                        verbose_name="Tipo de Destinatário",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("once", "Execução Única"),
                            ("daily", "Diário"),
                            ("weekly", "Semanal"),
                            ("monthly", "Mensal"),
                            ("yearly", "Anual"),
                        ],
                        max_length=10,
                        verbose_name="Frequência",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(verbose_name="Data/Hora de Início"),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data/Hora de Fim"
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Dia da Semana"
                    ),
                ),
                (
                    "day_of_month",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Dia do Mês"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Ativo"),
                            ("paused", "Pausado"),
                            ("completed", "Concluído"),
                            ("failed", "Falhou"),
                        ],
                        default="active",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "last_sent",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Último Envio"
                    ),
                ),
                (
                    "next_execution",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Próxima Execução"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scheduler.contact",
                        verbose_name="Contato",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scheduler.group",
                        verbose_name="Grupo",
                    ),
                ),
                (
                    "message_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scheduler.messagetemplate",
                        verbose_name="Template da Mensagem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensagem Agendada",
                "verbose_name_plural": "Mensagens Agendadas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "recipient",
                    models.CharField(max_length=100, verbose_name="Destinatário"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("sent", "Enviado"),
                            ("failed", "Falhou"),
                            ("delivered", "Entregue"),
                            ("read", "Lido"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Enviado em"),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Entregue em"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Mensagem de Erro"
                    ),
                ),
                (
                    "evolution_message_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="ID da Mensagem Evolution",
                    ),
                ),
                (
                    "scheduled_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scheduler.scheduledmessage",
                        verbose_name="Mensagem Agendada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Mensagem",
                "verbose_name_plural": "Logs de Mensagens",
                "ordering": ["-sent_at"],
            },
        ),
    ]
