# Generated by Django 5.0.6 on 2025-07-05 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagetemplate',
            options={'ordering': ['title'], 'verbose_name': 'Modelo de Mensagem', 'verbose_name_plural': 'Modelos de Mensagens'},
        ),
        migrations.RemoveField(
            model_name='group',
            name='description',
        ),
        migrations.RemoveField(
            model_name='group',
            name='group_id',
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='groups', to='scheduler.contact', verbose_name='Membros'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Número de Telefone'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nome do Grupo'),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='media_type',
            field=models.CharField(choices=[('text', 'Texto'), ('image', 'Imagem'), ('video', 'Vídeo'), ('document', 'Documento')], default='text', max_length=10, verbose_name='Tipo de Mídia'),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='scheduledmessage',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.contact', verbose_name='Contato'),
        ),
        migrations.AlterField(
            model_name='scheduledmessage',
            name='day_of_month',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30'), (31, '31')], null=True, verbose_name='Dia do Mês'),
        ),
        migrations.AlterField(
            model_name='scheduledmessage',
            name='day_of_week',
            field=models.IntegerField(blank=True, choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], null=True, verbose_name='Dia da Semana'),
        ),
        migrations.AlterField(
            model_name='scheduledmessage',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e Hora de Fim'),
        ),
        migrations.AlterField(
            model_name='scheduledmessage',
            name='frequency',
            field=models.CharField(choices=[('once', 'Uma vez'), ('daily', 'Diariamente'), ('weekly', 'Semanalmente'), ('monthly', 'Mensalmente'), ('yearly', 'Anualmente')], max_length=10, verbose_name='Frequência'),
        ),
        migrations.AlterField(
            model_name='scheduledmessage',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.group', verbose_name='Grupo'),
        ),
        migrations.AlterField(
            model_name='scheduledmessage',
            name='message_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.messagetemplate', verbose_name='Modelo de Mensagem'),
        ),
        migrations.AlterField(
            model_name='scheduledmessage',
            name='start_date',
            field=models.DateTimeField(verbose_name='Data e Hora de Início'),
        ),
        migrations.AlterField(
            model_name='scheduledmessage',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título do Agendamento'),
        ),
    ]
