# Generated by Django 5.0.6 on 2025-07-05 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_alter_messagetemplate_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagetemplate',
            options={'ordering': ['title'], 'verbose_name': 'Template de Mensagem', 'verbose_name_plural': 'Templates de Mensagens'},
        ),
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='group',
            name='group_id',
            field=models.CharField(default=1, max_length=100, unique=True, verbose_name='ID do Grupo no WhatsApp'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Número do Telefone'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome do Grupo'),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='media_type',
            field=models.CharField(choices=[('text', 'Texto'), ('image', 'Imagem'), ('document', 'Documento'), ('audio', 'Áudio')], default='text', max_length=10, verbose_name='Tipo de Mídia'),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='scheduledmessage',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.contact', verbose_name='Contato'),
        ),
        migrations.AlterField(
            model_name='scheduledmessage',
            name='day_of_month',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dia do Mês'),
        ),
        migrations.AlterField(
            model_name='scheduledmessage',
            name='day_of_week',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dia da Semana (0-6)'),
        ),
        migrations.AlterField(
            model_name='scheduledmessage',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora de Fim'),
        ),
        migrations.AlterField(
            model_name='scheduledmessage',
            name='frequency',
            field=models.CharField(choices=[('once', 'Execução Única'), ('daily', 'Diário'), ('weekly', 'Semanal'), ('monthly', 'Mensal'), ('yearly', 'Anual')], max_length=10, verbose_name='Frequência'),
        ),
        migrations.AlterField(
            model_name='scheduledmessage',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.group', verbose_name='Grupo'),
        ),
        migrations.AlterField(
            model_name='scheduledmessage',
            name='message_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.messagetemplate', verbose_name='Template da Mensagem'),
        ),
        migrations.AlterField(
            model_name='scheduledmessage',
            name='start_date',
            field=models.DateTimeField(verbose_name='Data/Hora de Início'),
        ),
        migrations.AlterField(
            model_name='scheduledmessage',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Título do Agendamento'),
        ),
    ]
